--require('trndr/utils')
require('settings')
require('keymaps')
require('plugins/lazy')
--require('trndr/plugins/feline')
--require('trndr/plugins/nvim-lspconfig')
--require('trndr/plugins/nvim-cmp')
