require('trndr/utils')
require('trndr/settings')
require('trndr/keymaps')
require('trndr/plugins/packer')
require('trndr/plugins/feline')
require('trndr/plugins/nvim-lspconfig')
require('trndr/plugins/nvim-cmp')
